
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package fool;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 15;
  public static final int AND = 18;
  public static final int LT = 12;
  public static final int SEMICOLON = 24;
  public static final int CLASS = 2;
  public static final int ELSE = 7;
  public static final int PLUS = 14;
  public static final int RBRACE = 23;
  public static final int RPAREN = 21;
  public static final int OR = 19;
  public static final int INT = 4;
  public static final int NOT = 17;
  public static final int IDENTIFIER = 26;
  public static final int RETURN = 8;
  public static final int TRUE = 9;
  public static final int IF = 6;
  public static final int LBRACE = 22;
  public static final int LPAREN = 20;
  public static final int GT = 13;
  public static final int INT_CONST = 27;
  public static final int COMMA = 25;
  public static final int EOF = 0;
  public static final int FALSE = 10;
  public static final int error = 1;
  public static final int ASSIGN = 16;
  public static final int EQ = 11;
  public static final int BOOL = 5;
  public static final int VOID = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CLASS",
  "VOID",
  "INT",
  "BOOL",
  "IF",
  "ELSE",
  "RETURN",
  "TRUE",
  "FALSE",
  "EQ",
  "LT",
  "GT",
  "PLUS",
  "TIMES",
  "ASSIGN",
  "NOT",
  "AND",
  "OR",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "SEMICOLON",
  "COMMA",
  "IDENTIFIER",
  "INT_CONST"
  };
}

